background_opacity: 0.9
#working_directory: "/mnt/Lenovo/College/4th-year-CSE/2nd-Term/3_network-programming/personal/pracitcal"

#reflow: false
font:
  size: 13.0
  normal:
    family: "MesloLGS NF"
window:
  padding:
    x: 2
    y: 10
  #dynamic_padding: true

cursor:
  style:
    shape: Beam
    vi_mode_style: None
