# theme = "modern"
icons = "awesome5"

[theme]
name = "modern"
[theme.overrides]
# idle_bg = "#25344ddf"
# separator = "\ue0b2"

[[block]]
block = "focused_window"
max_width = 20
show_marks = "visible"

# [[block]]
# block = "pacman"
# interval = 7200
# format = "{pacman} +{aur}"
# format_singular = "{both}"
# format_up_to_date = "✔️"
# critical_updates_regex = "(linux|linux-lts|linux-zen)"
# # aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
# aur_command = "paru -Qua"
# hide_when_uptodate = true

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"
# format = "{utilization} {boost}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "net"
format = "{speed_down;M*B} {speed_up;M*B}"
interval = 1

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "free"
# unit = "GB"
# format = "{icon} /{free}"
# interval = 20
# warning = 20.0
# alert = 10.0
# alert_absolute = true

# [[block]]
# block = "disk_space"
# path = "/mnt/Lenovo"
# info_type = "free"
# unit = "GB"
# format = "{icon} L{free}"
# interval = 20
# warning = 20.0
# alert = 10.0
# alert_absolute = true

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"
max_vol = 100
# driver = "alsa"
on_click = "pavucontrol"
headphones_indicator = true

# [[block]]
# block = "backlight"
# device = "intel_backlight"
# invert_icons = true
# root_scaling = 2.4


[[block]]
block = "battery"
format = "{percentage}"
full_format = ""
interval = 10
info = 50

[[block]]
block = "time"
interval = 20
format = "%a-%j %d/%m/%y %I:%M %p"

[[block]]
block = "toggle"

text = ""
command_state = "echo"
command_on = "swaymsg 'inhibit_idle open'"
icon_on = "eye"
command_off = "swaymsg 'inhibit_idle none'"
icon_off = "eye_slash"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "{layout}"
[block.mappings]
"English (US)" = "EN"
"Arabic (N/A)" = "Ara"

[[block]]
block = "custom"
command = "echo "
on_click = "pkill -USR1 nwg-drawer"
