# theme = "modern"

[icons]
icons = "awesome6"

[theme]
theme = "modern"
[theme.overrides]
# idle_bg = "#25344ddf"
# separator = "\ue0b2"

# [[block]]
# block = "focused_window"
# format = "$title.str(max_w:30) | "

[[block]]
block = "net"
format = " $icon ^icon_net_down$speed_down.eng(prefix:M) "
interval = 1
[[block.click]]
button = "left"
cmd = "gtk-launch iwgtk"

[[block]]
block = "cpu"

[[block]]
block = "time"
interval = 20
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %I:%M%p') "
short = " $icon $timestamp.datetime(f:%R) "
[[block.click]]
button = "left"
cmd = "gsimplecal"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
[block.mappings]
"English (US)" = "EN"
"Arabic (N/A)" = "Ar"

[[block]]
block = "toggle"
format = " $icon "
# text = ""
command_state = "swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused==true).inhibit_idle' | grep true"
command_on = "swaymsg 'inhibit_idle open'"
# icon_on = "eye"
command_off = "swaymsg 'inhibit_idle none'"
# icon_off = "eye_slash"

# [[block]]
# block = "sound"
# step_width = 2
# max_vol = 100
# on_click = "pavucontrol"
# headphones_indicator = true

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = ""
interval = 10


[[block]]
block = "custom"
command = "echo "
[[block.click]]
button = "left"
cmd = "wofi --show=drun --allow-images --allow-markup --insensitive --parse-search --define=key_expand=Right --width=60% --height=60%"
