fallback = ''
[matching]
'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'/Thorium/' = ''
'Slack' = ''
'thorium-jmbjodkbocgnllhjfdohoblibgdhcibe-Profile_1' = ''
'thorium-plgncniiolgjoediekkchhkpmgehjnee-Profile_2' = ''
'thorium-cifhbcnohmdccbgoicgdjpfamggdegmo-Profile_2' = ''
'thorium-cifhbcnohmdccbgoicgdjpfamggdegmo-Default' = ''
'thorium-faolnafnngnfdaknnbpnkhgohbobgegn-Profile_2' = ''
'FortiClient' = ''
'Code' = ''
'code-url-handler' = ''
'Spotify' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'dev.warp.Warp' = ''
'footclient' = ''
'mpv' = ''
'pcmanfm-qt' = ''
